CuyZ/Valinor

src/Type/Parser/LexingParser.php
Previously, `array_filter` would remove the integer value `0` from the
array.
See #1
=> fix: filter type symbols with strict string comparison

src/Mapper/Object/DateTimeObjectBuilder.php, tests/Integration/Mapping/Type/DateTimeMappingTest.php
I'm not sure I put these in the right place, but if there's a better place, let me know. 
I see this package being incredibly useful for automatically mapping data from databases into entities/value objects, so I hope that you'll consider this patch.
=> Fixes #39 - Adds MySQL TIMESTAMP and PgSQL DATETIME formats.

src/Definition/Repository/Cache/Compiler/AttributesCompiler.php, tests/Fixture/Attribute/NestedAttribute.php, tests/Fixture/Object/ObjectWithNestedAttributes.php, tests/Functional/Definition/Repository/Cache/Compiler/AttributesCompilerTest.php
In PHP 8.1 `new` in initializers were introduced which allows now to use nested attributes. The current implementation of [`AttributesCompiler`](https://github.com/CuyZ/Valinor/blob/master/src/Definition/Repository/Cache/Compiler/AttributesCompiler.php#L94) uses `var_export` which generates invalid PHP Code for cached PHP files.
Thanks to @Ocramius suggestion I was able to fix this issue using `serialize/unserialize`
=> Changed AttributesCompiler to use serializer/unserializer when compiling arguments

src/Library/Container.php, src/Mapper/Object/Argument.php, src/Mapper/Object/DateTimeObjectBuilder.php, src/Mapper/Object/MethodObjectBuilder.php, src/Mapper/Object/ObjectBuilder.php, src/Mapper/Object/ReflectionObjectBuilder.php, src/Mapper/Tree/Builder/ClassNodeBuilder.php, src/Type/Resolver/Exception/CannotResolveObjectTypeFromUnion.php, src/Type/Resolver/Exception/CannotResolveTypeFromUnion.php, src/Type/Resolver/Union/UnionObjectNarrower.php, src/Type/Types/Exception/ForbiddenMixedType.php, tests/Fake/Mapper/Object/FakeObjectBuilder.php, tests/Integration/Mapping/Fixture/NativeUnionOfObjects.php, tests/Integration/Mapping/Object/DateTimeMappingTest.php, tests/Integration/Mapping/Object/ObjectValuesMappingTest.php, tests/Integration/Mapping/Object/UnionOfObjectsMappingTest.php, tests/Unit/Cache/Compiled/CompiledPhpFileCacheTest.php, tests/Unit/Mapper/Object/MethodObjectBuilderTest.php, tests/Unit/Mapper/Object/ReflectionObjectBuilderTest.php
When the mapper needs to map a source to a union of objects, it will try
to guess which object it will map to, based on the needed arguments of
the objects, and the values contained in the source.
```php
final class UnionOfObjects
{
public readonly SomeFooObject|SomeBarObject $object;
}
final class SomeFooObject
{
public readonly string $foo;
}
final class SomeBarObject
{
public readonly string $bar;
}
// Will map to an instance of `SomeFooObject`
->mapper()
->map(UnionOfObjects::class, ['foo' => 'foo']);
// Will map to an instance of `SomeBarObject`
->mapper()
->map(UnionOfObjects::class, ['bar' => 'bar']);
```
=> feat: introduce automatic union of objects inferring during mapping

qa/PHPStan/Extension/ApiAndInternalAnnotationCheck.php
The regex matched `@api` or `internal<whitespace>`.
Now it matches `@` followed by `api` or `internal` followed by `<whitespace>`.
=> fix: correct regex that detects `@internal` or `@api` annotations

.github/dependabot.yml, .github/workflows/mutation.yml, .github/workflows/quality-assurance.yml, .github/workflows/tests.yml, composer.json, composer.lock, psalm.xml, src/Mapper/TreeMapper.php, tests/StaticAnalysis/Stub/A.php, tests/StaticAnalysis/can-infer-tree-mapper-results.php
This patch is mostly raised by the upgrade of `0.3.0` to `0.4.0` breaking BC (expected, but preventable).
In practice, Valinor is probably going to be used because of `TreeMapper#map(class-string<T>, mixed): T` in the grand majority of cases.
To cover this scenario, and prevent regressions, I introduced:
* testing against **locked** dependencies, so that we can pinpoint tiny upgrades that break `cuyz/valinor` as they come up
* automated dependency **widening** (I would prefer bumping, but that's really your decision)
* `vimeo/psalm` type inference testing
* better types around `TreeMapper#map()`, so that it works without coupling `cuyz/valinor` to a specific `vimeo/psalm` version (the type declarations for the majority scenario are in the code, without any need for plugins)
=> Better type inference, improved test coverage throughout locked dependencies, automated dependency upgrades

src/Definition/ParameterDefinition.php, src/Definition/Repository/Cache/Compiler/ParameterDefinitionCompiler.php, src/Definition/Repository/Reflection/ReflectionParameterDefinitionBuilder.php, src/Definition/Repository/Reflection/ReflectionTypeResolver.php, src/Mapper/Object/MethodObjectBuilder.php, tests/Fake/Definition/FakeParameterDefinition.php, tests/Fake/Definition/Repository/FakeFunctionDefinitionRepository.php, tests/Functional/Definition/Repository/Cache/Compiler/ClassDefinitionCompilerTest.php, tests/Functional/Definition/Repository/Cache/Compiler/FunctionDefinitionCompilerTest.php, tests/Integration/Mapping/VariadicParameterMappingTest.php, tests/Unit/Definition/ParameterDefinitionTest.php
Using variadic parameters is now handled properly by the library,
meaning the following example will run:
```php
{
/** @var string[] */
private array $values;
public function __construct(string ...$values)
{
$this->values = $values;
}
}
->mapper()
->map(SomeClass::class, ['foo', 'bar', 'baz']);
```
=> feat: handle variadic parameters in constructors

src/Mapper/Source/Modifier/CamelCaseKeys.php, tests/Unit/Mapper/Source/Modifier/CamelCaseKeysTest.php
When using the camel key modifier with a source like:
```
{
"foo_bar": "test",
"test": [
{ "foo": "bar" },
{ "foo": "bar" }
]
}
```
The camel key modifier throws an exception. 
This fixes the behaviour
=> Fix camel key modifier when used with non associative array

src/Definition/Attributes.php, src/Definition/AttributesContainer.php, src/Definition/CombinedAttributes.php, src/Definition/DoctrineAnnotations.php, src/Definition/EmptyAttributes.php, src/Definition/NativeAttributes.php, src/Mapper/Object/Factory/AttributeObjectBuilderFactory.php, src/Mapper/Tree/Visitor/AttributeShellVisitor.php, tests/Fake/Definition/FakeAttributes.php, tests/Fake/Definition/FakeNonEmptyAttributes.php, tests/Unit/Definition/AttributesContainerTest.php
There was no benefits having the return type as `iterable`, but it would
make it harder to use the result of the method.
=> misc!: change `Attributes::ofType` return type to `array`

src/Utility/Reflection/Reflection.php, tests/Unit/Utility/Reflection/ReflectionTest.php
As requested in #118, this PR provides support for these prefixes.
=> Feature: Support for `psalm-` and `phpstan-` prefixes in `@var`, `@param` and `@return` annotations

README.md, src/Definition/Repository/Cache/Compiler/TypeCompiler.php, src/Type/FloatType.php, src/Type/Parser/Lexer/NativeLexer.php, src/Type/Parser/Lexer/Token/FloatValueToken.php, src/Type/Parser/Lexer/Token/NativeToken.php, src/Type/Types/Exception/InvalidFloatValue.php, src/Type/Types/Exception/InvalidFloatValueType.php, src/Type/Types/FloatValueType.php, src/Type/Types/NativeFloatType.php, tests/Functional/Definition/Repository/Cache/Compiler/TypeCompilerTest.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Integration/IntegrationTest.php, tests/Integration/Mapping/Object/ScalarValuesMappingTest.php, tests/Integration/Mapping/Object/UnionValuesMappingTest.php, tests/Unit/Type/Resolver/Union/UnionScalarNarrowerTest.php, tests/Unit/Type/Types/FloatValueTypeTest.php, tests/Unit/Type/Types/IntegerValueTypeTest.php, tests/Unit/Type/Types/NativeFloatTypeTest.php, tests/Unit/Type/Types/ShapedArrayTypeTest.php, tests/Unit/Type/Types/StringValueTypeTest.php
Allows the usage of float values, as follows:
```php
class Foo
{
/** @var 404.42|1337.42 */
public readonly float $value;
}
```
=> feat: handle float value type 

src/Mapper/Object/DateTimeObjectBuilder.php, tests/Integration/Mapping/Object/DateTimeMappingTest.php
Hi, here I propose the support for dates without time on `DateTimeObjectBuilder`.
=> DateTimeObjectBuilder: support dates without time

src/Utility/Reflection/Reflection.php, tests/Fixture/Object/ObjectWithPropertyPromotion.php, tests/Unit/Utility/Reflection/ReflectionTest.php
Hello, I encountered a problem while trying out the interesting library. I use a lot of dtos with property promotions, my typing was not recognized there and eg. `non-empty-string` was ignored (missing mapping error message).
```php
final class PublishMessage
{
public function __construct(
/** @var non-empty-string */
public readonly string $text
) {
}
}
```
I dug deeper and saw what the problem was. I noticed that in the case of property promotion, the @var annotation is ignored when the constructor is used.
I am of the opinion that with promoted properties the parameters should be treated exactly as properties and thus @var annotation are allowed. So do other tools like phpstan/psalm etc.
I created a first fix, which I would be happy to improve with your feedback.
=> support @var annotion for property promotion parameter

src/Cache/Warmup/RecursiveCacheWarmupService.php, src/Library/Container.php, src/Type/Types/ClassStringType.php, tests/Integration/Cache/CacheWarmupTest.php, tests/Unit/Type/Types/ClassStringTypeTest.php
The Warmup will now recursively handle interface and their class
implementations. It is also done in a more clever way: instead of
warming up all properties and constructors, it takes only what is
needed.
=> feat: improve cache warmup

src/Mapper/Tree/Shell.php, tests/Unit/Mapper/Tree/Builder/TreeNodeTest.php, tests/Unit/Mapper/Tree/ShellTest.php
The path is no longer an empty string, the string `*root*` is now
returned.
=> misc: add fixed value for root node path

src/Mapper/MappingError.php, src/Mapper/Tree/Message/MessagesFlattener.php, tests/Integration/Mapping/MappingErrorTest.php
Hi, the [message customization](https://github.com/CuyZ/Valinor#message-customization) is great, but a first feedback without it would be very useful to speed up debugging.
Before and after this PR:
```diff
-CuyZ\Valinor\Mapper\MappingError: Could not map type `array{foo: string, bar: int}` with the given source.
+CuyZ\Valinor\Mapper\MappingError: Could not map type `array{foo: string, bar: int}` with the given source. First error is:
+Path: foo
+Given value: array (empty)
+Error: Cannot be empty and must be filled with a value matching type `string`.
```
=> MappingError: expose the first error in Exception message

src/Definition/NativeAttributes.php, tests/Fixture/Attribute/PropertyTargetAttribute.php, tests/Fixture/Object/ObjectWithAttributes.php, tests/Functional/Definition/Repository/Cache/Compiler/AttributesCompilerTest.php
First of all, I wanted to thank everyone who has contributed to this amazing library! Good job guys!
I created this PR after dealing with some issues while trying to use `symfony/validator` with Valinor:
```php
use App\Request\ParamConverter\RequestQueryInterface;
use Symfony\Component\Validator\Constraints\Range;
class TestQuery implements RequestQueryInterface
{
public function __construct(
#[Range(min: 10)]
public readonly int $page,
) {
}
}
```
After calling `map()` method I received this exception:
```
Attribute "Symfony\Component\Validator\Constraints\Range" cannot target parameter (allowed targets: method, property)
```
So basically, all Symfony's constraint attributes are declared with these flags:
```php
#[Attribute(Attribute::TARGET_PROPERTY | Attribute::TARGET_METHOD | …
```
=> Extract promoted property/param attribute based on the attribute target flags

docs/pages/mapping/construction-strategy.md, src/Mapper/Object/DynamicConstructor.php, src/Mapper/Object/Exception/InvalidConstructorClassTypeParameter.php, src/Mapper/Object/Exception/InvalidConstructorReturnType.php, src/Mapper/Object/Exception/MissingConstructorClassTypeParameter.php, src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php, src/Mapper/Object/Factory/DateTimeObjectBuilderFactory.php, src/Mapper/Object/FunctionObjectBuilder.php, tests/Integration/Mapping/ConstructorRegistrationMappingTest.php, tests/Unit/Mapper/Object/FunctionObjectBuilderTest.php
In some situations the type handled by a constructor is only known at
runtime, in which case the constructor needs to know what class must be
used to instantiate the object.
For instance, an interface may declare a static constructor that is then
implemented by several child classes. One solution would be to register
the constructor for each child class, which leads to a lot of
boilerplate code and would require a new registration each time a new
child is created. Another way is to use the attribute
`\CuyZ\Valinor\Mapper\Object\DynamicConstructor`.
When a constructor uses this attribute, its first parameter must be a
string and will be filled with the name of the actual class that the
mapper needs to build when the constructor is called. Other arguments
may be added and will be mapped …
=> feat: introduce attribute `DynamicConstructor`

src/Type/Parser/Lexer/Token/ArrayToken.php, src/Type/Parser/Lexer/TokenStream.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Integration/Mapping/Object/ShapedArrayValuesMappingTest.php
Allows the following syntax:
```php
/**
* @var array{
* 	   foo: string,
*     bar: int,
* }
*/
```
Fixes #205
=> fix: allow trailing comma in shaped array

src/Cache/Compiled/CompiledPhpFileCache.php, tests/Unit/Cache/Compiled/CompiledPhpFileCacheTest.php
seems to be necessary with concurrent requests
=> Ensure cached files do not already exist

src/Cache/Compiled/CompiledPhpFileCache.php, src/Cache/FileSystemCache.php, tests/Integration/Cache/CacheInjectionTest.php
Method `\CuyZ\Valinor\Cache\FileSystemCache::get()` was not properly
looping on all delegates, leading to the values not being fetched from
the cache files and resulting in `null` (the default value) being
returned in some cases. Because of the following algorithm, the cache
entry was populated again, so the cache was not really working here.
```php
if ($this->cache->has($key)) {
$entry = $this->cache->get($key);
if ($entry) {
return $entry;
}
}
$class = $this->delegate->for($type);
$this->cache->set($key, $class);
return $class;
```
=> fix: correctly fetch file system cache entries

src/Cache/ChainCache.php, src/Cache/Compiled/CompiledPhpFileCache.php, src/Cache/FileSystemCache.php, src/Cache/FileWatchingCache.php, src/Cache/KeySanitizerCache.php, src/Cache/RuntimeCache.php, tests/Fake/Cache/FakeCache.php, tests/Fake/Cache/FakeFailingCache.php
Fixes `User Deprecated: Method "Psr\SimpleCache\CacheInterface::get()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "CuyZ\Valinor\Cache\..." now to avoid errors or add an explicit @return annotation to suppress this message.` reported by `symfony/error-handler`.
=> Fix psr/simple-cache deprecations

src/Definition/FunctionDefinition.php, src/Definition/Repository/Cache/Compiler/FunctionDefinitionCompiler.php, src/Definition/Repository/Reflection/ReflectionFunctionDefinitionRepository.php, src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php, tests/Fake/Definition/FakeFunctionDefinition.php, tests/Functional/Definition/Repository/Cache/Compiler/FunctionDefinitionCompilerTest.php, tests/Integration/Mapping/ConstructorRegistrationMappingTest.php
The `MethodObjectBuilder` was incorrectly used when a registered constructor is a static anonymous functions — it was handled like a static method closure `Class::method(...)` and would yield errors like this:
Error: Call to undefined method stdClass::CuyZ\Valinor\Tests\Integration\Mapping\{closure}()
PHP Reflection does not provide any way of telling static functions and closures of static methods apart, other than checking for the name `{closure}`. We check that `{closure}` is actually the last part of the fully-qualified name, instead of just checking that the string ends with `{closure}`.
=> fix: handle constructors that are static anonymous functions

qa/Psalm/Plugin/TreeMapperPsalmPlugin.php
`getAtomicTypes` should be used to iterate over the types of a Union, removing the call to `getChildNodes` since it's out of place and may be deprecated in psalm v5.
=> Switch to using getAtomicTypes

docs/pages/mapping/handled-types.md, src/Mapper/Tree/Shell.php, src/Type/Parser/Exception/Constant/ClassConstantCaseNotFound.php, src/Type/Parser/Exception/Constant/MissingClassConstantCase.php, src/Type/Parser/Exception/Constant/MissingClassConstantColon.php, src/Type/Parser/Exception/Constant/MissingSpecificClassConstantCase.php, src/Type/Parser/Lexer/ClassGenericLexer.php, src/Type/Parser/Lexer/Token/ClassNameToken.php, src/Type/Parser/Lexer/Token/GenericClassNameToken.php, src/Type/Types/UnionType.php, src/Utility/TypeHelper.php, tests/Fixture/Object/ObjectWithConstants.php, tests/Fixture/Object/ObjectWithConstantsIncludingEnums.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Integration/Mapping/Fixture/NativeUnionValues.php, tests/Integration/Mapping/Object/ConstantValuesMappingTest.php, tests/Integration/Mapping/Object/UnionValuesMappingTest.php, tests/Unit/Mapper/Tree/ShellTest.php, tests/Unit/Type/Parser/Lexer/Token/GenericClassNameTokenTest.php, tests/Unit/Type/Types/UnionTypeTest.php, tests/Unit/Utility/Reflection/ReflectionTest.php
This notation is mainly useful when several cases in constants of a
class share a common prefix.
```php
final class SomeClassWithConstants
{
public const FOO = 1337;
public const BAR = 'bar';
public const BAZ = 'baz';
}
$mapper = (new MapperBuilder())->mapper();
$mapper->map('SomeClassWithConstants::BA*', 1337); // error
$mapper->map('SomeClassWithConstants::BA*', 'bar'); // ok
$mapper->map('SomeClassWithConstants::BA*', 'baz'); // ok
```
Closes #119
=> feat: add support for class constant type

src/Cache/Compiled/CompiledPhpFileCache.php
The return value of `uniqid()` is not very random and easily guessable. While this likely does not introduce any issues in CompiledPhpFileCache, the fact that `uniqid()` is often mis-used in locations where actual randomness is a hard requirement, makes this a red flag.
Replace the use of `uniqid()` to generate a random filename by hexadecimal encoded `random_bytes(16)`, giving 128 Bits of randomness, making the value unguessable in practice and preventing the `CompiledPhpFileCache` from showing up when searching for `uniqid()`.
=> misc: do not use `uniqid()`

.gitattributes
The lock file is not useful for downstream consumers and requires more than 200kB of data to be unnecessarily transmitted.
---------------
Also: Is the `/docs/` directory useful within the `vendor/` directory or can that one also be ignored?
=> Add additional `export-ignore` files to `.gitattributes`

src/Type/Parser/Lexer/NativeLexer.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php
This PR adds basic support for strict array tokens, just so I can keep the new section in the Psalm docs mentioning Valinor as a way to validate strict arrays :)
Phpstan should also support strict array syntax once https://github.com/phpstan/phpdoc-parser/pull/161 is merged.
=> feat: add support for `strict-array` type

docs/pages/message-customization.md, docs/pages/validation.md, src/Mapper/MappingError.php, src/Mapper/Tree/Message/Formatter/CallbackMessageFormatter.php, src/Mapper/Tree/Message/Messages.php, src/Mapper/Tree/Message/MessagesFlattener.php, tests/Fake/Mapper/Tree/Message/FakeNodeMessage.php, tests/Fake/Mapper/Tree/Message/Formatter/FakeMessageFormatter.php, tests/Unit/Mapper/Tree/Message/Formatter/AggregateMessageFormatterTest.php, tests/Unit/Mapper/Tree/Message/Formatter/CallbackMessageFormatterTest.php, tests/Unit/Mapper/Tree/Message/Formatter/PlaceHolderMessageFormatterTest.php, tests/Unit/Mapper/Tree/Message/MessagesTest.php
The class `\CuyZ\Valinor\Mapper\Tree\Message\MessagesFlattener` is now deprecated in favor of `\CuyZ\Valinor\Mapper\Tree\Message\Messages`.
The behaviour of this new class is the same as the previous one, except for a new method to add formatters, and a new static factory to recursively flatten messages of a node.
```php
try {
return (new \CuyZ\Valinor\MapperBuilder())
->mapper()
->map(SomeClass::class, [/* … * /]);
} catch (\CuyZ\Valinor\Mapper\MappingError $error) {
// Get a flatten list of all messages through the whole nodes tree
$messages = \CuyZ\Valinor\Mapper\Tree\Message\Messages::flattenFromNode(
$error->node()
);
// Formatters can be added and will be applied on all messages
$messages = $messages->formatWith(
new \CuyZ\Valinor\Mapper\Tree\Message\Formatter\MessageMapFormatter([ …
```
=> feat: introduce new helper class to list messages

docs/pages/mapping/type-strictness.md, src/Library/Container.php, src/Library/Settings.php, src/Mapper/Object/FilledArguments.php, src/Mapper/Tree/Builder/ArrayNodeBuilder.php, src/Mapper/Tree/Builder/ClassNodeBuilder.php, src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/ListNodeBuilder.php, src/Mapper/Tree/Builder/ScalarNodeBuilder.php, src/Mapper/Tree/Builder/ShapedArrayNodeBuilder.php, src/Mapper/Tree/Builder/StrictNodeBuilder.php, src/Mapper/Tree/Builder/UnionNodeBuilder.php, src/MapperBuilder.php, tests/Integration/Mapping/Other/FlexibleCastingMappingTest.php, tests/Integration/Mapping/Other/PermissiveTypesMappingTest.php, tests/Integration/Mapping/Other/StrictMappingTest.php, tests/Integration/Mapping/Other/SuperfluousKeysMappingTest.php, tests/Unit/MapperBuilderTest.php
The flexible mode has been deprecated in favor of three modes with
distinct roles.
1. **The flexible casting**
Changes the behaviours explained below:
```php
$flexibleMapper = (new \CuyZ\Valinor\MapperBuilder())
->enableFlexibleCasting()
->mapper();
// ---
// Scalar types will accept non-strict values; for instance an
// integer type will accept any valid numeric value like the
// *string* "42".
$flexibleMapper->map('int', '42');
// => 42
// ---
// List type will accept non-incremental keys.
$flexibleMapper->map('list<int>', ['foo' => 42, 'bar' => 1337]);
// => [0 => 42, 1 => 1338]
// ---
// If a value is missing in a source for a node that accepts `null`,
// the node will be filled with `null`.
$flexibleMapper->map(
'array{foo: string, bar: null|string}',
['foo' => 'foo'] // `bar` is …
```
=> feat: split mapper flexible mode in three distinct modes

src/Mapper/Object/FilledArguments.php, tests/Integration/Mapping/SingleNodeMappingTest.php
=> fix: allow mapping `null` to single node nullable type

src/Library/Container.php, src/Mapper/Object/Factory/DateTimeZoneObjectBuilderFactory.php, src/Mapper/Tree/Message/DefaultMessage.php, tests/Integration/Mapping/Object/DateTimeZoneMappingTest.php
```php
try {
->mapper()
->map(DateTimeZone::class, 'Jupiter/Europa');
} catch (MappingError $exception) {
$error = $exception->node()->messages()[0];
// Value 'Jupiter/Europa' is not a valid timezone.
echo $error->toString();
}
```
=> feat: add constructor for `DateTimeZone` with error support

docs/pages/other/static-analysis.md, psalm.xml, qa/Psalm/ValinorPsalmPlugin.php
The plugin can now be registered like this in the `psalm.xml` file:
```xml
<plugins>
<pluginClass class="CuyZ\Valinor\QA\Psalm\ValinorPsalmPlugin"/>
</plugins>
```
=> qa: enhance Psalm plugin registration for Valinor

docs/mkdocs.yml, docs/pages/mapping/arguments-mapping.md, docs/pages/other/static-analysis.md, qa/PHPStan/Extension/ArgumentsMapperPHPStanExtension.php, qa/PHPStan/Extension/TreeMapperPHPStanExtension.php, qa/PHPStan/valinor-phpstan-configuration.php, qa/Psalm/Plugin/ArgumentsMapperPsalmPlugin.php, qa/Psalm/Plugin/TreeMapperPsalmPlugin.php, qa/Psalm/ValinorPsalmPlugin.php, src/Library/Container.php, src/Mapper/ArgumentsMapper.php, src/Mapper/ArgumentsMapperError.php, src/Mapper/MappingError.php, src/Mapper/TypeArgumentsMapper.php, src/Mapper/TypeTreeMapper.php, src/Mapper/TypeTreeMapperError.php, src/MapperBuilder.php, tests/Integration/Mapping/Closure/ArgumentsMappingTest.php, tests/StaticAnalysis/can-infer-callable-arguments-mapper-result.php, tests/Unit/Mapper/TreeMapperErrorTest.php, tests/Unit/Mapper/TypeTreeMapperTest.php
This new mapper can be used to ensure a source has the right shape before calling a function/method.
The mapper builder can be configured the same way it would be with a tree mapper, for instance to customize the type strictness.
```php
$someFunction = function(string $foo, int $bar): string {
return "$foo / $bar";
}
try {
$arguments = (new \CuyZ\Valinor\MapperBuilder())
->argumentsMapper()
->mapArguments($someFunction, [
'foo' => 'some value',
'bar' => 42,
]);
// some value / 42
echo $someFunction(...$arguments);
} catch (\CuyZ\Valinor\Mapper\MappingError $error) {
// Do something…
}
```
Any callable can be given to the arguments mapper:
```php
final class SomeController
{
public static function someAction(string $foo, int $bar): string
{
return "$foo / $bar";
}
}
try {
$arguments = (new …
```
=> feat: introduce mapper to map arguments of a callable

src/Type/Parser/Lexer/NativeLexer.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php
Psalm went backward on the introduction of the new `strict-array` type, see https://github.com/vimeo/psalm/pull/8701 for more information.
=> misc!: remove support for `strict-array` type

src/Mapper/ArgumentsMapper.php, src/Mapper/TreeMapper.php, src/Mapper/TypeArgumentsMapper.php, src/Mapper/TypeTreeMapper.php, src/MapperBuilder.php
This change also impacts all callables that can be given to the mapper builder — they also need to be pure.
Although it reduces the scope of the mappers, it greatly improves their safety.
=> misc!: mark tree mapper and arguments mapper as `@pure`

qa/PHPStan/valinor-phpstan-configuration.php
Fixes the following exception when including `vendor/cuyz/valinor/qa/PHPStan/valinor-phpstan-configuration.php`.
```
In Resolver.php line 111:
[_PHPStan_9a6ded56a\Nette\DI\ServiceCreationException]
Service (CuyZ\Valinor\QA\PHPStan\Extension\ArgumentsMapperPHPStanExtension::__construct()): Class 'CuyZ\Valinor\QA\PHPStan\Extension\ArgumentsMapperPHPStanExtension' not found.
```
=> Fix Class not found exception in phpstan extension

src/Mapper/TreeMapper.php
In situation when $signature is just type of class-string without exact class, return type expected by phpstan is mixin. With this change phpstan will expect return type object.
Bit more context here https://github.com/phpstan/phpstan/issues/8443
=> misc: improve return type signature for `TreeMapper`

src/Cache/FileWatchingCache.php, src/Definition/Repository/Cache/CacheClassDefinitionRepository.php, src/Definition/Repository/Cache/CacheFunctionDefinitionRepository.php, src/Mapper/Object/Factory/CacheObjectBuilderFactory.php
From PSR-16 specs:
> It is recommended that has() is only to be used for cache warming type
purposes and not to be used within your live applications operations
for get/set, as this method is subject to a race condition where your
has() will return true and immediately after, another script can
remove it, making the state of your app out of date.
Closes #241
=> misc: prevent multiple cache round-trip

docs/pages/how-to/infer-interfaces.md, rector.php, src/Cache/Warmup/RecursiveCacheWarmupService.php, src/Definition/ClassDefinition.php, src/Definition/Repository/Cache/Compiler/ClassDefinitionCompiler.php, src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php, src/Library/Container.php, src/Library/Settings.php, src/Mapper/Object/ArgumentsValues.php, src/Mapper/Tree/Builder/ClassNodeBuilder.php, src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/ObjectImplementations.php, src/Mapper/Tree/Builder/ProxyClassNodeBuilder.php, src/Mapper/Tree/Exception/CannotInferFinalClass.php, src/MapperBuilder.php, tests/Fake/Definition/FakeClassDefinition.php, tests/Functional/Definition/Repository/Cache/Compiler/ClassDefinitionCompilerTest.php, tests/Integration/Mapping/ClassInheritanceInferringMappingTest.php, tests/Unit/Definition/ClassDefinitionTest.php
It is now possible to infer abstract or parent classes the same way it
can be done for interfaces.
Example with an abstract class:
```php
abstract class SomeAbstractClass
{
public string $foo;
public string $bar;
}
final class SomeChildClass extends SomeAbstractClass
{
public string $baz;
}
$result = (new \CuyZ\Valinor\MapperBuilder())
->infer(
SomeAbstractClass::class,
fn () => SomeChildClass::class
)
->mapper()
->map(SomeAbstractClass::class, [
'foo' => 'foo',
'bar' => 'bar',
'baz' => 'baz',
]);
assert($result instanceof SomeChildClass);
assert($result->foo === 'foo');
assert($result->bar === 'bar');
assert($result->baz === 'baz');
```
Fixes #143
=> feat: add support for class inferring

docs/pages/usage/object-construction.md, src/Mapper/Object/ArgumentsValues.php, tests/Integration/Mapping/Object/NullableMappingTest.php, tests/Integration/Mapping/Other/SuperfluousKeysMappingTest.php, tests/Integration/Mapping/SingleNodeMappingTest.php
It is now possible, again, to use an array for a single node (single
class property or single constructor argument), if this array has one
value with a key matching the argument/property name.
This is a revert of a change that was introduced in a previous commit:
see hash 72cba320f582c7cda63865880a1cbf7ea292d2b1
Closes #269
=> feat: allow usage of array input for single node during mapping

src/Mapper/Tree/Builder/UnionNodeBuilder.php, tests/Integration/Mapping/Object/UnionOfObjectsMappingTest.php
=> fix: properly handle union of `null` and objects

src/Type/Types/ArrayKeyType.php, tests/Unit/Type/Types/ArrayKeyTypeTest.php
=> fix: make `array-key` type match `mixed`

src/Mapper/Tree/Builder/TreeNode.php, src/Type/Types/NativeFloatType.php, tests/Integration/Mapping/Object/ScalarValuesMappingTest.php, tests/Integration/Mapping/Object/UnionValuesMappingTest.php, tests/Unit/Type/Types/NativeFloatTypeTest.php
A float property/parameter will accept an integer value in PHP, even when `strict_types` is enabled. PHPStan and Psalm also accept the case below. To make it consistent, the mapper will now accept integer values in float types.
```php
->mapper()
->map('float', 42); // returns `42.0`
```
Fixes #360
=> fix: allow integer values in float types

rector.php, src/Mapper/Source/Exception/InvalidJson.php, src/Mapper/Source/JsonSource.php
This brings two improvements:
- The reason for the JSON parsing failure is visible in the stack trace / $previous exception, allowing the developer to determine whether the parsing failure was caused by a syntax error, invalid UTF-8 sequence or something else.
- The JSON string `null` (which decodes to `null`) is no longer erroneously rejected as invalid. Instead it is rejected, because it is not iterable, slightly improving the error reporting.
=> misc: catch `json_encode` exception to help identifying parsing errors

src/Definition/Repository/Cache/Compiler/ParameterDefinitionCompiler.php
`is_scalar` should just be an inverted `is_object` check, instead.
=> Avoid using unserialize when caching NULL default values

src/Mapper/Object/DateTimeFormatConstructor.php, tests/Integration/Mapping/Object/DateTimeMappingTest.php
I'm not sure this is the _right_ fix but timestamps can technically be negative numbers. I have some dates that I'm importing that range back to 1920 and am currently getting an error that `Value {source_value} does not match any of 'non-empty-string', 'positive-int'` for the value `-450734400`.
If you agree with this change I can expand the PR, update the tests, etc.
=> Allow for timestamps before the epoch

src/Definition/Repository/Cache/Compiler/TypeCompiler.php, src/Mapper/Object/Exception/InvalidConstructorReturnType.php, src/Type/Types/UnresolvableType.php, tests/Unit/Definition/Repository/Reflection/ReflectionClassDefinitionRepositoryTest.php, tests/Unit/Type/Types/UnresolvableTypeTest.php
Because `UnresolvableType` can be applied to any property, parameter or function/method return type, it can be present in a class definition hierarchy. This class definition can then be cached for better application performance, meaning these `UnresolvableType` will be present in the cache entry. This is a problem because an exception contains a lot of information, including reflection instances which can not be serialized and can break caching mechanisms that rely on serialization.
`UnresolvableType` extending `LogicException` was not necessary, so it is removed and the code relying on it has been adapted.
=> fix: remove exception inheritance from `UnresolvableType`

src/Definition/NativeAttributes.php, src/Definition/Repository/Cache/Compiler/AttributesCompiler.php, src/Mapper/Object/Exception/InvalidConstructorReturnType.php, src/Type/Types/UnresolvableType.php
Following up eaa1283, fixes an issue where cache mechanism could break
when relying on serialization.
=> fix: remove previous exception from UnresolvableType

src/Type/Parser/Lexer/AliasLexer.php, tests/Integration/Mapping/ClassNameCollisionTestCollision.php, tests/Integration/Mapping/Fixture/Error.php
=> fix: handle class name collision while parsing types inside a class

composer.json, src/Cache/ChainCache.php, src/Cache/Compiled/CompiledPhpFileCache.php, src/Cache/FileSystemCache.php, src/Cache/FileWatchingCache.php, src/Cache/KeySanitizerCache.php, src/Cache/Warmup/RecursiveCacheWarmupService.php, src/Cache/WarmupCache.php, src/Library/Container.php, tests/Fake/Cache/FakeCacheWithWarmup.php, tests/Integration/Cache/CacheWarmupTest.php, tests/Unit/Cache/Compiled/CompiledPhpFileCacheTest.php, tests/Unit/Cache/Compiled/FileWatchingCacheTest.php, tests/Unit/Cache/FileSystemCacheTest.php
Calling the mapper warmup will now go through all caches layers and run a warmup process. When using `FileSystemCache` that is provided by the library, the directories required by this cache will be created.
This should fix an issue that could occur when race conditions happened in an app with a lot of traffic.
Fixes #401
=> fix: improve cache warmup by creating required directories

src/Utility/String/StringFormatter.php, src/Utility/String/StringFormatterError.php, tests/Unit/Utility/String/StringFormatterTest.php
If `intl.use_exceptions=1`, ext/intl will throw an `\IntlException` that was not yet handled and caused `StringFormatter::format()` to violate its contract to throw `StringFormatterError` in case of errors.
=> fix: Fix the handling of invalid formats if `intl.use_exceptions=1`

src/Definition/AttributesContainer.php, src/Definition/NativeAttributes.php, src/Definition/Repository/Cache/Compiler/AttributesCompiler.php, tests/Unit/Definition/AttributesContainerTest.php
Attributes are now loaded in a lazy way, preventing an error from happening when attributes were compiled in the cache, but not present when using the mapper during the runtime.
This could happen for instance with attributes used to generate documentation of an API: they are loaded as a development dependency, then the cache is warmed up during deployment, so they are present in the mapper compiled cache; but these attributes are missing from the live version of the application, so they cannot be accessed.
This commit helps to prevent a fatal error from happening in this kind of situation.
Fixes #393
=> fix: load attributes lazily during runtime and cache access

docs/pages/how-to/deal-with-dates.md, src/Library/Settings.php, src/Mapper/Object/DateTimeFormatConstructor.php, src/MapperBuilder.php, tests/Integration/Mapping/Object/DateTimeMappingTest.php, tests/Unit/MapperBuilderTest.php
This commit adds default support for microseconds in the RFC 3339 format.
The references to the “Atom” format have been updated to RFC 3339 which is identical to the Atom format, but uses a reference that is not PHP-specific.
=> feat: Support microseconds in the Atom / RFC 3339 / ISO 8601 format

tests/Integration/Mapping/Source/SourceTest.php
Previously when the YAML extension was not installed, the test was skipped /
errored entirely, as the data provider is invalid:
> 1) Error
> The data provider specified for CuyZ\Valinor\Tests\Integration\Mapping\Source\SourceTest::test_sources_are_mapped_properly is invalid.
> CuyZ\Valinor\Mapper\Source\Exception\YamlExtensionNotEnabled: The PHP YAML extension is not enabled.
> /pwd/src/Mapper/Source/YamlSource.php:38
> /pwd/src/Mapper/Source/Source.php:55
> /pwd/tests/Integration/Mapping/Source/SourceTest.php:74
Now the YAML source will simply not be provided.
=> qa: Fix SourceTest without YAML extension

tests/Unit/Mapper/Tree/Message/NodeMessageTest.php
This test requires the intl extension instead of the shim to work.
=> test: Add `@requires` to NodeMessageTest::test_custom_locale_is_used()

rector.php
This no longer triggers and thus is not required to be skipped.
=> qa: Remove MixedTypeRector exception in rector.php

src/Definition/Exception/InvalidTypeAliasImportClass.php, src/Utility/Reflection/DocParser.php, tests/Integration/Mapping/Object/LocalTypeAliasMappingTest.php
Hi, this used to work in `1.5.0`, looks like multi line local alias shaped array is not parsed properly.
=> Add failing test for local alias shaped array multi line

src/Mapper/Source/Modifier/Mapping.php, src/Mapper/Source/Modifier/PathMapping.php, src/Mapper/Source/Source.php, tests/Unit/Mapper/Source/Modifier/PathMappingTest.php
The following now works properly:
```php
\CuyZ\Valinor\Mapper\Source\Source::array([0 => 'foo'])
->map([
'0' => 'some_key'
]);
```
Fixes #430
=> fix: handle integer key in path mapping modifier

src/Utility/Reflection/DocParser.php, tests/Integration/Mapping/Object/LocalTypeAliasMappingTest.php
Hi there,
thanks for the tool it's really helpful 👍🏼 (although I'm not sure we are using it correctly 🙈 )
The latest update however broke our usage due to a bug in #424  :(
and my understanding/observation makes me think it is not intended.
We hope this patch is okay as we'd like to keep our local comments on the classes:
https://github.com/nextcloud/spreed/blob/f60017eb778730874615a955b99510624c074534/lib/Signaling/Responses/DialOut.php#L29-L47
The problem is that the new list of strings you check is a bit flawed. This can be observed by `var_dump($cases);` after:
https://github.com/CuyZ/Valinor/blob/f4884cf319774726bd7ccf7fe9c00c0f0177330e/src/Utility/Reflection/DocParser.php#L74
<details>
```
array(14) {
[0]=>
string(311) "Comment:
Some comment before types
* @psalm-type …
```
=> Allow comments on classes

docs/pages/usage/type-reference.md, src/Definition/Repository/Cache/Compiler/TypeCompiler.php, src/Type/Parser/Lexer/Token/NativeToken.php, src/Type/Types/NonNegativeIntegerType.php, tests/Functional/Definition/Repository/Cache/Compiler/TypeCompilerTest.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Integration/Mapping/Object/ScalarValuesMappingTest.php, tests/Unit/Type/Types/NonNegativeIntegerTypeTest.php
Non-negative integer can be used as below. It will accept any value equal to or greater than zero.
```php
{
/** @var non-negative-int */
public int $nonNegativeInteger;
}
```
Closes #434
=> feat: handle non-negative integer type

docs/pages/usage/type-reference.md, src/Definition/Repository/Cache/Compiler/TypeCompiler.php, src/Type/Parser/Lexer/Token/NativeToken.php, src/Type/Types/NonPositiveIntegerType.php, tests/Functional/Definition/Repository/Cache/Compiler/TypeCompilerTest.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Integration/Mapping/Object/ScalarValuesMappingTest.php, tests/Unit/Type/Types/NonPositiveIntegerTypeTest.php
Non-positive integer can be used as below. It will accept any value equal to or lower than zero.
```php
{
/** @var non-positive-int */
public int $nonPositiveInteger;
}
```
=> feat: handle non-positive integer type

src/Type/Types/IntegerRangeType.php, src/Type/Types/IntegerValueType.php, src/Type/Types/NativeIntegerType.php, src/Type/Types/NonNegativeIntegerType.php, src/Type/Types/PositiveIntegerType.php, tests/Integration/Mapping/Other/FlexibleCastingMappingTest.php
=> fix: allow leading zeros in numeric string in flexible mode

src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/Normalizer/NormalizerTest.php
The same object can now exist several times in an array, an iterable or in several properties of a class.
The normalizer will not detect it as a circular reference anymore.
Fixes #472
=> fix: detect circular references linearly through objects

src/Normalizer/Formatter/JsonFormatter.php, tests/Integration/Normalizer/NormalizerTest.php
=> fix: properly encode scalar value in JSON normalization

docs/pages/how-to/use-custom-object-constructors.md, docs/pages/serialization/extending-normalizer.md, src/Definition/MethodDefinition.php, src/Definition/Repository/Cache/Compiler/MethodDefinitionCompiler.php, src/Definition/Repository/Reflection/ReflectionMethodDefinitionBuilder.php, src/Mapper/Object/Constructor.php, src/Mapper/Object/Exception/InvalidConstructorMethodWithAttributeReturnType.php, src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php, src/Mapper/Object/FilteredObjectBuilder.php, tests/Fake/Definition/FakeMethodDefinition.php, tests/Integration/Mapping/ConstructorAttributeMappingTest.php, tests/Integration/Mapping/EnumConstructorAttributeMappingTest.php, tests/Unit/Definition/MethodDefinitionTest.php
This attribute can be assigned to any method inside an object, to automatically mark the method as a constructor for the class. This is a more convenient way of registering constructors than using the `MapperBuilder::registerConstructor` method, although it does not replace it.
The method targeted by a `Constructor` attribute must be public, static and return an instance of the class it is part of.
```php
final readonly class Email
{
// When another constructor is registered for the class, the native
// constructor is disabled. To enable it again, it is mandatory to
// explicitly register it again.
#[\CuyZ\Valinor\Mapper\Object\Constructor]
public function __construct(public string $value) {}
#[\CuyZ\Valinor\Mapper\Object\Constructor]
public static function createFrom(
string $userName, …
```
=> feat: introduce `Constructor` attribute

docs/pages/serialization/common-transformers-examples.md, docs/pages/serialization/extending-normalizer.md, src/MapperBuilder.php, src/Normalizer/AsTransformer.php, src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/Normalizer/AsTransformerAttributeTest.php
This attribute can be used to automatically register a transformer attribute.
```php
namespace My\App;
#[\CuyZ\Valinor\Normalizer\AsTransformer]
#[\Attribute(\Attribute::TARGET_PROPERTY)]
final class DateTimeFormat
{
public function __construct(private string $format) {}
public function normalize(\DateTimeInterface $date): string
{
return $date->format($this->format);
}
}
final readonly class Event
{
public function __construct(
public string $eventName,
#[\My\App\DateTimeFormat('Y/m/d')]
public \DateTimeInterface $date,
) {}
}
->normalizer(\CuyZ\Valinor\Normalizer\Format::array())
->normalize(new \My\App\Event(
eventName: 'Release of legendary album',
date: new \DateTimeImmutable('1971-11-08'),
));
// [
//     'eventName' => 'Release of legendary …
```
=> feat: introduce `AsTransformer` attribute

docs/pages/usage/type-reference.md, src/Library/Container.php, src/Mapper/Object/FilteredObjectBuilder.php, src/Mapper/Tree/Builder/CasterProxyNodeBuilder.php, src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/NativeClassNodeBuilder.php, src/Mapper/Tree/Builder/NullNodeBuilder.php, src/Mapper/Tree/Builder/TreeNode.php, src/Mapper/Tree/Builder/UnionNodeBuilder.php, src/Mapper/Tree/Exception/SourceIsNotNull.php, src/Mapper/Tree/Exception/TooManyResolvedTypesFromUnion.php, src/Mapper/Tree/Message/DefaultMessage.php, tests/Integration/Mapping/Object/NullableMappingTest.php, tests/Integration/Mapping/Object/UnionOfObjectsMappingTest.php, tests/Integration/Mapping/UnionMappingTest.php
The algorithm used by the mapper to narrow a union type has been greatly improved, and should cover more edge-cases that would previously prevent the mapper from performing well.
If an interface, a class or a shaped array is matched by the input, it will take precedence over arrays or scalars.
```php
->mapper()
->map(
signature: 'array<int>|' . Color::class,
source: [
'red' => 255,
'green' => 128,
'blue' => 64,
],
); // Returns an instance of `Color`
```
When superfluous keys are allowed, if the input matches several interfaces, classes or shaped array, the one with the most children node will be prioritized, as it is considered the most specific type:
```php
->allowSuperfluousKeys()
->mapper()
->map(
// Even if the …
```
=> feat: improve union type narrowing during mapping

src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/Normalizer/NormalizerTest.php
=> fix: properly handle `ArrayObject` normalization

src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php, src/Mapper/Object/Factory/ReflectionObjectBuilderFactory.php, src/Type/Parser/Factory/LexingTypeParserFactory.php, src/Type/Parser/Lexer/NativeLexer.php, src/Type/Parser/Lexer/ObjectLexer.php, src/Utility/Reflection/Reflection.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Unit/Type/Parser/Lexer/NativeLexerTest.php
This change aims to reduce the number of calls made to the global class autoloader, by limiting the class existence checks during type parsing.
See: #427
=> misc: reduce number of calls to class autoloader during type parsing

src/Type/CombiningType.php, src/Type/Parser/Lexer/Token/ClassNameToken.php, src/Type/Types/ArrayKeyType.php, src/Type/Types/IntersectionType.php, src/Type/Types/UnionType.php, tests/Functional/Type/Parser/Lexer/GenericLexerTest.php, tests/Integration/Mapping/Object/ScalarValuesMappingTest.php, tests/Integration/Mapping/Other/FlexibleCastingMappingTest.php, tests/Unit/Type/Types/ArrayKeyTypeTest.php, tests/Unit/Type/Types/IntersectionTypeTest.php, tests/Unit/Type/Types/UndefinedObjectTypeTest.php, tests/Unit/Type/Types/UnionTypeTest.php
=> feat: allow mapping to `array-key` type

src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php, src/Type/Types/UnresolvableType.php, tests/Integration/Mapping/Object/LocalTypeAliasMappingTest.php
Allows usage of `@phpstan-import-type` and `@psalm-import-type` from interfaces:
```php
/**
* @phpstan-type SomeAlias = array{foo: string, bar: int}
*/
interface InterfaceWithPhpStanLocalAlias { }
/**
* @phpstan-import-type SomeAlias from InterfaceWithPhpStanLocalAlias
*/
{
/** @var SomeAlias */
public $value;
}
->mapper()
->map(SomeClass::class, [
'foo' => 'bar',
'bar' => 42,
]);
```
Fixes #353
=> feat: handle type importation from interface

src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/ObjectImplementations.php, tests/Integration/Cache/CacheInjectionTest.php, tests/Integration/Cache/CacheWarmupTest.php, tests/Integration/Mapping/InterfaceInferringMappingTest.php
This commit changes the way interface inferring is done.
Previously, the whole set of information for all interfaces was loaded everytime the library was used, which could lead to performance issue for no reason.
Now, when an interface must be inferred, only information about this interface will be loaded.
=> fix: load needed information only during interface inferring

docs/pages/how-to/infer-interfaces.md, docs/pages/how-to/use-custom-object-constructors.md, infection.json.dist, src/Definition/ClassDefinition.php, src/Definition/Exception/InvalidTypeAliasImportClass.php, src/Definition/Exception/InvalidTypeAliasImportClassType.php, src/Definition/Exception/UnknownTypeAliasImport.php, src/Definition/Repository/Cache/CacheClassDefinitionRepository.php, src/Definition/Repository/ClassDefinitionRepository.php, src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php, src/Library/Container.php, src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php, src/Mapper/Object/Factory/DateTimeObjectBuilderFactory.php, src/Mapper/Object/Factory/DateTimeZoneObjectBuilderFactory.php, src/Mapper/Object/FunctionObjectBuilder.php, src/Mapper/Tree/Builder/FilteredObjectNodeBuilder.php, src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/NativeClassNodeBuilder.php, src/Mapper/Tree/Builder/ObjectNodeBuilder.php, src/Mapper/Tree/Exception/InterfaceHasBothConstructorAndInfer.php, src/Type/Types/InterfaceType.php, tests/Fake/Definition/Repository/FakeClassDefinitionRepository.php, tests/Integration/Mapping/ConstructorRegistrationMappingTest.php, tests/Unit/Type/Types/InterfaceTypeTest.php
By default, the mapper cannot instantiate an interface, as it does not
know which implementation to use. To do so, the `MapperBuilder::infer()`
method can be used, but it is cumbersome in most cases.
It is now also possible to register a constructor for an interface, in
the same way as for a class.
Because the mapper cannot automatically guess which implementation can
be used for an interface, it is not possible to use the `Constructor`
attribute, the `MapperBuilder::registerConstructor()` method must be
used instead.
In the example below, the mapper is taught how to instantiate an
implementation of `UuidInterface` from package `ramsey/uuid`:
```php
->registerConstructor(
// The static method below has return type `UuidInterface`;
// therefore, the …
```
=> feat: handle interface constructor registration

docs/pages/usage/type-reference.md, qa/PHPStan/Extension/TreeMapperPHPStanExtension.php, src/Definition/Repository/Cache/Compiler/TypeCompiler.php, src/Mapper/Tree/Builder/ShapedArrayNodeBuilder.php, src/Type/Parser/Exception/Iterable/ShapedArrayClosingBracketMissing.php, src/Type/Parser/Exception/Iterable/ShapedArrayInvalidUnsealedType.php, src/Type/Parser/Exception/Iterable/ShapedArrayUnexpectedTokenAfterSealedType.php, src/Type/Parser/Exception/Iterable/ShapedArrayWithoutElementsWithSealedType.php, src/Type/Parser/Lexer/NativeLexer.php, src/Type/Parser/Lexer/Token/ArrayToken.php, src/Type/Parser/Lexer/Token/TripleDotsToken.php, src/Type/Types/ArrayKeyType.php, src/Type/Types/ShapedArrayType.php, tests/Functional/Definition/Repository/Cache/Compiler/TypeCompilerTest.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Integration/Mapping/Object/ShapedArrayValuesMappingTest.php, tests/Integration/Mapping/Other/PermissiveTypesMappingTest.php, tests/Integration/Mapping/Other/StrictMappingTest.php, tests/Integration/Mapping/UnionMappingTest.php, tests/Unit/Type/Types/ShapedArrayTypeTest.php
This syntax enables an extension of the shaped array type by allowing additional values that must respect a certain type.
```php
$mapper = (new \CuyZ\Valinor\MapperBuilder())->mapper();
// Default syntax can be used like this:
$mapper->map(
'array{foo: string, ...array<string>}',
[
'foo' => 'foo',
'bar' => 'bar', // ✅ valid additional value
]
);
$mapper->map(
'array{foo: string, ...array<string>}',
[
'foo' => 'foo',
'bar' => 1337, // ❌ invalid value 1337
]
);
// Key type can be added as well:
$mapper->map(
'array{foo: string, ...array<int, string>}',
[
'foo' => 'foo',
42 => 'bar', // ✅ valid additional key
]
);
$mapper->map(
'array{foo: string, ...array<int, string>}',
[
'foo' => 'foo',
'bar' => 'bar' // ❌ invalid key
]
);
// Advanced types can be used:
$mapper->map(
"array{
'en_US': …
```
=> feat: introduce unsealed shaped array syntax

src/Definition/Repository/Reflection/TypeResolver/ClassImportedTypeAliasResolver.php, src/Definition/Repository/Reflection/TypeResolver/ClassLocalTypeAliasResolver.php, src/Definition/Repository/Reflection/TypeResolver/ClassParentTypeResolver.php, src/Definition/Repository/Reflection/TypeResolver/ClassTemplatesResolver.php, src/Definition/Repository/Reflection/TypeResolver/FunctionReturnTypeResolver.php, src/Definition/Repository/Reflection/TypeResolver/ParameterTypeResolver.php, src/Definition/Repository/Reflection/TypeResolver/PropertyTypeResolver.php, src/Type/Parser/Lexer/Annotations.php, src/Type/Parser/Lexer/TokenizedAnnotation.php, tests/Functional/Definition/Repository/Reflection/TypeResolver/ClassLocalTypeAliasResolverTest.php, tests/Functional/Definition/Repository/Reflection/TypeResolver/PropertyTypeResolverTest.php, tests/Unit/Type/Parser/Lexer/AnnotationsTest.php
The following annotation now works properly:
```php
/**
* @phpstan-type Address = array{street?: string, city: string}
* @phpstan-type User = array{name: non-empty-string, address: Address}
*/
{
public function __construct(
/** @var User */
public $value,
) {}
}
->mapper()
->map(SomeClass::class, [
'name' => 'John Doe',
'address' => [
'street' => 'Bron-Yr-Aur',
'city' => 'SY20 8QA, Machynlleth',
],
]);
```
Fixes #308
Fixes #428
=> fix: properly handle nested local type aliases

src/Mapper/Tree/Builder/UnionNodeBuilder.php, tests/Integration/Mapping/UnionMappingTest.php
Version 1.11 revamped union types but also deleted a fast path present in 1.10. In our use cases with many large objects with many nullable properties, this caused execution times to nearly double, especially with XDebug enabled.
The following test case sees its execution time drop from ~6.7 seconds to ~3.6 seconds on my local machine with the included patch. Profiling the test sees a reduction of node build calls to nearly half the original value.
```php
<?php
declare(strict_types=1);
namespace CuyZ\Valinor\Tests\Integration\Mapping;
use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\Mapper\Source\Source;
use CuyZ\Valinor\Tests\Integration\IntegrationTestCase;
final class LotsOfObjectsMappingTest extends IntegrationTestCase
{
public function test_can_map_lots_of_objects(): void
{ …
```
=> fix: skip node build for NullType when value is not null

src/Definition/Repository/AttributesRepository.php, src/Definition/Repository/Reflection/ReflectionAttributesRepository.php, src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php, src/Definition/Repository/Reflection/ReflectionFunctionDefinitionRepository.php, src/Definition/Repository/Reflection/ReflectionMethodDefinitionBuilder.php, src/Definition/Repository/Reflection/ReflectionParameterDefinitionBuilder.php, src/Definition/Repository/Reflection/ReflectionPropertyDefinitionBuilder.php, src/Library/Container.php, src/Library/Settings.php, src/Utility/Reflection/Reflection.php, tests/Fake/Definition/FakeAttributes.php, tests/Functional/Definition/Repository/Cache/Compiler/AttributesCompilerTest.php, tests/Functional/Definition/Repository/Cache/Compiler/ClassDefinitionCompilerTest.php, tests/Functional/Definition/Repository/Reflection/ReflectionAttributesRepositoryTest.php, tests/Functional/Definition/Repository/Reflection/ReflectionClassDefinitionRepositoryTest.php, tests/Functional/Definition/Repository/Reflection/ReflectionFunctionDefinitionRepositoryTest.php
This change aims to reduce the memory usage, as well as the compiled cache size for classes that heavily rely on attributes that are not used by this library, for instance `OpenAPI` attributes.
Fixes #525
=> misc: exclude unneeded attributes in class/function definitions

.github/workflows/mutation.yml, .github/workflows/tests.yml, src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/Normalizer/NormalizerTest.php
When I use transformers
```php
->registerTransformer(fn (\Ds\Set $v) => $v->toArray())
->registerTransformer(fn(Value $v) => $v->get())
->normalizer(\CuyZ\Valinor\Normalizer\Format::json())
```
My `\Ds\Set<Value>` is normalized to `array<Value>` but the Value is then ignored since the serialization is not recursive for the `Set`.
This fixes it.
Initially, I wanted to make this work for all `IteratorAggregate`s and `Iterator`s but with then `'iterable class'` case does not pass since it is designed to serialize its properties and not inner Iterator.
=> feat: support normalizing `Ds\Collection`

docs/pages/how-to/deal-with-dates.md, src/Library/Settings.php, src/Mapper/Object/DateTimeFormatConstructor.php, tests/Integration/Mapping/Object/DateTimeMappingTest.php, tests/Unit/MapperBuilderTest.php
Prior to this patch, this would require a custom constructor in the form of:
```php
static fn(float | int $timestamp): DateTimeImmutable => new
DateTimeImmutable(sprintf("@%d", $timestamp)),
```
This bypasses the datetime format support of Valinor entirely. This is required because the library does not support floats as valid DateTimeInterface input values.
This PR adds support for floats and registers timestamp.microseconds (U.u) as a valid default format.
=> feat: add microseconds support to timestamp format

docs/pages/serialization/normalizer.md, docs/pages/usage/type-strictness-and-flexibility.md
Hi, and thanks for the library!
Spotted these errors while reading the docs.
=> doc: fix some typos

src/Normalizer/Transformer/ValueTransformersHandler.php, tests/Integration/Normalizer/NormalizerTest.php
Currently, when I have some docblock for callable in Transformer, the `TransformerHasInvalidCallableParameter` is thrown. I want to allow more specific callable, phpstan requires it (`missingType.callable`).
=> fix(transformers): allow phpdoc for callables

src/Normalizer/ArrayNormalizer.php, src/Normalizer/Formatter/JsonFormatter.php, src/Normalizer/Transformer/EmptyObject.php, src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/Normalizer/NormalizerTest.php
Objects that yield no value or have no property will now properly be formatted into `{}` instead of `[]`.
fixes #542
=> fix: properly format empty object with JSON normalizer

tests/Integration/Mapping/ConstructorRegistrationMappingTest.php
In this test, Valinor considers two disjoint input types as colliding.
Similar to https://github.com/CuyZ/Valinor/pull/487 ( ffe0f0f21290ff6469da5c723172b9afc6aeba7d ), this scenario was detected while trying to map multiple constructors for XML structures that may present different data depending on singular/plural entries found:
```xml
<Invoices>
<Invoice>
<Item><Price>123</Price></Item>
</Invoice>
<Invoice>
<Item><Price>456</Price></Item>
<Item><Price>789</Price></Item>
</Invoice>
</Invoices>
```
In #487, we attempted to map a single constructor using `array{foo: T|list<T>}`, while in this patch, we found the issue because we attempted to attack the problem by declaring separate constructors that would work on `array{foo: T}` and `array{foo: list<T>}` disjointly, but failed to do so …
=> Failing test: constructors with input `array{key: T}` and `array{key: list<T>}` considered colliding

src/Type/Parser/Lexer/TokenizedAnnotation.php
Currently 1.13.0 breaks psalm:
```
psalm --no-cache --threads=$(nproc)
Target PHP version: 8.1 (set by config file).
Scanning files...
Uncaught Exception: Psalm\Exception\DocblockParseException Invalid string non-empty-list<string>>
Emitted in …/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/CommentAnalyzer.php:357
Stack trace in the forked worker:
#0 …/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/CommentAnalyzer.php(109): Psalm\Internal\Analyzer\CommentAnalyzer::splitDocLine('...')
#1 …/vendor-bin/psalm/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/CommentAnalyzer.php(63): Psalm\Internal\Analyzer\CommentAnalyzer::arrayToDocblocks(Object(PhpParser\Comment\Doc), Object(Psalm\Internal\Scanner\ParsedDocblock), Object(Psalm\Internal\Scanner\FileScanner), …
```
=> fix(lexer): Fix typo in TokenizedAnnotation breaking psalm

src/Mapper/Tree/Shell.php, tests/Integration/Mapping/UnionMappingTest.php
This was broken in commit
https://github.com/CuyZ/Valinor/commit/0479532fbc96fca35dcbfb4c1f5a9ef63e7625c5 as withType may be called in union type context.
First calling withValue() to set an int value and then updating the type with withType() does not trigger the float cast, in turn causing a mapping error.
Developed by: Social Deal (@socialdeal)
=> Regression: Fix int and float compatibility in union types

src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/NonRegression/NormalizeEnumDoesNotBreakMapperTest.php, tests/Integration/Normalizer/NormalizerTest.php
=> fix: prevent cache corruption when normalizing and mapping to enum

src/Mapper/ArgumentsMapper.php, src/Mapper/Tree/Message/MessageBuilder.php, src/Mapper/TreeMapper.php, src/Mapper/TypeArgumentsMapper.php, src/Mapper/TypeTreeMapper.php, src/MapperBuilder.php
Due to the current overhead required to make PHPStan and Psalm work with the pure feature, these requirements have been removed.
Since PHPStan and Psalm are unfortunately unable to automatically detect whether callable values provided to `MapperBuilder` are pure, users are forced to manually add `@pure` annotations.
This decision aims to strike a fair balance between the library's strictness and user experience.
Fixes #540, #550
Closes #563
=> misc: remove "pure" requirements from several methods

qa/Psalm/ValinorPsalmPlugin.php, tests/Fake/Definition/FakeFunctionDefinition.php, tests/Fake/Definition/FakeParameterDefinition.php, tests/Fake/Mapper/Tree/Builder/FakeNodeBuilder.php, tests/Fake/Mapper/Tree/Builder/FakeTreeNode.php, tests/Fake/Type/FakeType.php, tests/StaticAnalysis/inferring-types-with-plugin.php
Implicitly nullable parameter types are deprecated in PHP 8.4:
https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
=> misc: fix PHP 8.4 deprecations

src/Mapper/Tree/Shell.php, tests/Unit/Mapper/Tree/ShellTest.php
The current implementation keeps a reference in each `Shell` to its parent in order to know if it's the root node and be able to generate the its path.
The problem with this design is that this creates circular references, making the job difficult for PHP to free these objects from memory.
Since we build a child from the parent object we create the path by duplicating the path of the parent and adding the child name.
=> misc: remove the need to keep a reference to the parent node

src/Normalizer/Formatter/JsonFormatter.php, src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/Normalizer/NormalizerTest.php
=> fix: normalize empty iterable object as empty array in JSON

src/Mapper/Object/ArgumentsValues.php, src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/ObjectNodeBuilder.php, src/Mapper/Tree/Shell.php, tests/Integration/Mapping/InterfaceInferringMappingTest.php, tests/Integration/Mapping/Object/ObjectValuesMappingTest.php, tests/Unit/Mapper/Tree/ShellTest.php
=> fix: properly handle superfluous keys when source is an iterable

src/Mapper/Object/Exception/CannotFindObjectBuilder.php, src/Mapper/Object/Exception/CannotParseToDateTime.php, src/Mapper/Object/Exception/InvalidSource.php, src/Mapper/Tree/Builder/ArrayNodeBuilder.php, src/Mapper/Tree/Builder/Node.php, src/Mapper/Tree/Builder/ObjectNodeBuilder.php, src/Mapper/Tree/Exception/CannotResolveTypeFromUnion.php, src/Mapper/Tree/Exception/InvalidArrayKey.php, src/Mapper/Tree/Exception/InvalidListKey.php, src/Mapper/Tree/Exception/InvalidNodeValue.php, src/Mapper/Tree/Exception/MissingNodeValue.php, src/Mapper/Tree/Exception/SourceIsEmptyArray.php, src/Mapper/Tree/Exception/SourceIsEmptyList.php, src/Mapper/Tree/Exception/SourceIsNotNull.php, src/Mapper/Tree/Exception/SourceMustBeIterable.php, src/Mapper/Tree/Exception/TooManyResolvedTypesFromUnion.php, src/Mapper/Tree/Exception/UnexpectedKeysInSource.php, src/Mapper/Tree/Message/ErrorMessage.php, src/Mapper/Tree/Message/MessageBuilder.php, src/Mapper/Tree/Message/NodeMessage.php, src/Mapper/Tree/Message/UserlandError.php, src/Utility/String/StringFormatter.php, tests/Unit/Utility/String/StringFormatterTest.php
The error messages being exceptions do not add any value when using the
messages in a `MappingError`. Therefore, the backtrace creation is a
heavy, unnecessary, operation.
All internal messages have been changed to reflect this.
Throwing custom exceptions during object creations still works.
=> misc: remove `Throwable` inheritance from `ErrorMessage`

tests/Integration/IntegrationTestCase.php
PHPUnit commit
https://github.com/sebastianbergmann/phpunit/commit/8f0f8205e3a38675392da55afc573c6bb6a43f4e makes the `runTest` method used by the integration tests private. `runBare` however is still public, so we can use that.
Because `runBare` will also call pre-test and post-test hooks, we have to be careful not to end in an infinite loop.
Thought: Tests should potentially be rewritten to be wrapped in a closure instead, which runs the test with and without cache. This however would take a lot more time to implement than this quick fix. This would break the dependency on PHPUnit internal code. We could then add a post-test hook to verify a cache was used.
=> qa: Use runBare method now that runTest is made private

docs/pages/index.md, docs/pages/other/app-and-framework-integration.md, docs/pages/other/performance-and-caching.md, docs/pages/project/upgrading.md, docs/pages/serialization/common-transformers-examples.md, docs/pages/serialization/extending-normalizer.md, docs/pages/serialization/normalizer.md, docs/pages/serialization/normalizing-json.md, src/MapperBuilder.php, src/NormalizerBuilder.php, tests/Integration/IntegrationTestCase.php, tests/Integration/NonRegression/NormalizeEnumDoesNotBreakMapperTest.php, tests/Integration/Normalizer/AsTransformerAttributeTest.php, tests/Integration/Normalizer/CommonExamples/CustomObjectNormalizationTest.php, tests/Integration/Normalizer/CommonExamples/DateFormatFromAttributeTest.php, tests/Integration/Normalizer/CommonExamples/DateFormatFromGlobalTransformerTest.php, tests/Integration/Normalizer/CommonExamples/IgnoreAttributeTest.php, tests/Integration/Normalizer/CommonExamples/ObjectKeysToSnakeCaseFromAttributeTest.php, tests/Integration/Normalizer/CommonExamples/ObjectKeysToSnakeCaseTest.php, tests/Integration/Normalizer/CommonExamples/RenamePropertyFromAttributeTest.php, tests/Integration/Normalizer/CommonExamples/UppercaseFromAttributeTest.php, tests/Integration/Normalizer/CommonExamples/VersionTransformerTest.php, tests/Integration/Normalizer/NormalizerCompiledCodeTest.php, tests/Integration/Normalizer/NormalizerTest.php, tests/Integration/Normalizer/StreamNormalizerTest.php, tests/StaticAnalysis/PHPStan/v1/inferring-normalizer-types.php, tests/StaticAnalysis/inferring-normalizer-types.php, tests/Unit/MapperBuilderTest.php, tests/Unit/NormalizerBuilderTest.php
The `NormalizerBuilder` class has been introduced and will now be the main entry to instantiate normalizers. Therefore, the methods in `MapperBuilder` that used to configure and return normalizers have been removed.
This decision aims to make a clear distinction between the mapper and the normalizer configuration API, where confusion could arise when using both.
The `NormalizerBuilder` can be used like this:
```php
$normalizer = (new \CuyZ\Valinor\NormalizerBuilder())
->registerTransformer(
fn (\DateTimeInterface $date) => $date->format('Y/m/d')
)
->normalizer(\CuyZ\Valinor\Normalizer\Format::array())
->normalize($someData);
```
=> feat!: introduce `NormalizerBuilder` as the main entry for normalizers

src/Compiler/Native/ValueNode.php
the previous implementation was
- harder to read for the dev
- needed PHPStan ignores as hard to analyze
- produced 2 infection timed out mutants (because code was changed into endless loops)
the new impl fixes this problems
=> Simplify ValueNode implementation

docs/pages/other/static-analysis.md, docs/pages/project/changelog.md, docs/pages/project/changelog/version-2.0.0.md, docs/pages/project/upgrading.md, phpstan.neon.dist, qa/PHPStan/Extension/SuppressPureErrors.php, qa/PHPStan/valinor-phpstan-suppress-pure-errors.php, qa/Psalm/valinor-psalm-suppress-pure-errors.xml, src/Mapper/ArgumentsMapper.php, src/Mapper/TreeMapper.php, src/Mapper/TypeArgumentsMapper.php, src/Mapper/TypeTreeMapper.php, src/MapperBuilder.php, src/Normalizer/ArrayNormalizer.php, src/Normalizer/JsonNormalizer.php, src/Normalizer/Normalizer.php, src/Normalizer/StreamNormalizer.php, src/NormalizerBuilder.php
The `@pure` annotations were removed in the previous commit b15d1a50c3783b47b743385431899f2696ffebd6 for the following reasons:
> Due to the current overhead required to make PHPStan and Psalm work
> with the pure feature, these requirements have been removed.
>
> Since PHPStan and Psalm are unfortunately unable to automatically
> detect whether callable values provided to `MapperBuilder` are pure,
> users are forced to manually add `@pure` annotations.
>
> This decision aims to strike a fair balance between the library's
> strictness and user experience.
After a discussion with `@pure` aficionados, the decision has been made to re-introduce them. This time, is is possible to easily suppress the errors reported by PHPStan and Psalm by using plugins provided out of the box by this library. …
=> misc!: add purity markers in `MapperBuilder` and `NormalizerBuilder`

src/Mapper/Tree/Exception/ValueConverterHasNoArgument.php
This was a mistake made during the creation of the exception.
=> misc: mark exception as `@internal`

src/Type/Parser/Lexer/TokensExtractor.php, tests/Functional/Definition/Repository/Reflection/TypeResolver/ClassLocalTypeAliasResolverTest.php
=> fix: properly extract `=` token when reading types

src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php, tests/Fixture/Object/AbstractObjectWithInterface.php, tests/Functional/Definition/Repository/Cache/Compiler/ClassDefinitionCompilerTest.php, tests/Functional/Definition/Repository/Reflection/ReflectionClassDefinitionRepositoryTest.php
When building class definitions, only methods that will be used by the library are now included.
This change aims to increase performance when working with classes that declare a lot of methods that have no value in Valinor's definitions, for instance `\Carbon\Carbon`.
Fixes #667
=> misc: exclude unneeded methods when building class definition

.github/workflows/mutation.yml, composer.json
Adds the `--with-uncovered` option when running Infection.
Reference: https://github.com/infection/infection/releases/tag/0.31.0
=> qa: include uncovered code when running Infection
