CuyZ/Valinor

src/Utility/Reflection/Reflection.php, tests/Integration/Mapping/Type/ScalarValuesMappingTest.php, tests/Integration/Mapping/Type/UnionValuesMappingTest.php
=> fix: resolve single/double quotes when parsing doc-block type

.gitattributes
Like so https://github.com/szepeviktor/Valinor/blob/patch-1/stubs/Psr/SimpleCache/CacheInterface.php.stub
=> Syntax highlight stub files

src/Type/Parser/Lexer/Token/ArrayToken.php, tests/Integration/Mapping/Type/ShapedArrayValuesMappingTest.php
=> fix: handle shaped array integer key

composer.json, src/Utility/Package.php
=> misc: use composer runtime API

.github/workflows/mutation.yml, .github/workflows/quality-assurance.yml, .github/workflows/tests.yml
`8.1` is a floating point number in YAML
=> Fix CI config

composer.json, tests/Integration/Mapping/Type/EnumValuesMappingTest.php, tests/Unit/Mapper/Tree/Builder/EnumNodeBuilderTest.php, tests/Unit/Type/Types/EnumTypeTest.php
This enables full PHP 8.1 support 🎉
=> misc: raise PHPStan version

src/Definition/AttributesContainer.php, src/Mapper/Object/Factory/AttributeObjectBuilderFactory.php, tests/Integration/Mapping/Attribute/ObjectBuilderStrategyMappingTest.php
Without this change I needed to define the Valinor attributes first, otherwise an undefined index error occurred (was using Doctrine annotations in our project).
=> fix: Attributes now combine correctly with foreign attributes

src/Utility/Reflection/Reflection.php, tests/Unit/Utility/Reflection/ReflectionTest.php
=> Ensure mixed types remain valid

composer.json
=> fix: change license in `composer.json`

tests/Integration/Mapping/Object/DateTimeMappingTest.php
Addresses https://github.com/CuyZ/Valinor/issues/44
=> Strengthen datetime mapping tests

docs/pages/mapping/handled-types.md, src/Definition/Repository/Cache/Compiler/TypeCompiler.php, src/Type/Parser/Lexer/Token/NativeToken.php, src/Type/Types/Exception/InvalidNumericStringValue.php, src/Type/Types/NumericStringType.php, tests/Functional/Definition/Repository/Cache/Compiler/TypeCompilerTest.php, tests/Functional/Type/Parser/Lexer/NativeLexerTest.php, tests/Integration/Mapping/Object/ScalarValuesMappingTest.php, tests/Unit/Type/Types/NumericStringTypeTest.php
=> Added numeric-string type

tests/Integration/Mapping/MappingErrorTest.php
Following up https://github.com/CuyZ/Valinor/pull/139#discussion_r930641057
=> test: use exception expectation API for mapping error test

src/Cache/KeySanitizerCache.php, src/Library/Container.php, tests/Unit/Cache/KeySanitizerCacheTest.php, tests/Unit/MapperBuilderTest.php
@see https://www.php-fig.org/psr/psr-16/#12-definitions
Fixes #197
=> fix: prevent illegal characters in PSR-16 cache keys

docs/pages/project/changelog.md, docs/pages/project/changelog/version-1.0.0.md
=> release: version 1.0.0

src/Mapper/Tree/Builder/ClassNodeBuilder.php, src/Mapper/Tree/Builder/ShapedArrayNodeBuilder.php, src/Mapper/Tree/Exception/UnexpectedShapedArrayKeys.php, tests/Integration/Mapping/Object/ObjectValuesMappingTest.php, tests/Integration/Mapping/Other/ShapedArrayMappingTest.php
=> fix: keep nested errors when superfluous keys are detected

src/Mapper/Tree/Builder/TreeNode.php
=> fix: do not re-validate single node with existing error

src/Type/Types/Factory/ValueTypeFactory.php, src/Utility/Reflection/Reflection.php, src/Utility/ValueDumper.php
=> fix: use PHP 8.0 Polyfill where needed

.github/workflows/quality-assurance.yml
- safe YAML literal style
- using 1 command
- find FIXME-s
- whole words only
cons: no output on success just a ✔️
=> Improve TODO handling

.github/workflows/quality-assurance.yml, README.md
Without extended regexp it should be `'\(todo\|fixme\)'`
=> Make TODO checker work again

docs/pages/how-to/use-custom-object-constructors.md, src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php, tests/Integration/Mapping/ConstructorRegistrationMappingTest.php
=> fix: properly handle class static constructor for other class

src/Mapper/Object/ArgumentsValues.php, src/Mapper/Tree/Builder/ObjectNodeBuilder.php, tests/Integration/Mapping/SingleNodeMappingTest.php
=> fix: keep input path when error occurs in single node

src/Mapper/Object/Exception/InvalidConstructorReturnType.php, tests/Integration/Mapping/ConstructorRegistrationMappingTest.php, tests/Integration/Mapping/Fixture/SimpleObjectWithGeneric.php
=> fix: display useful error message for invalid constructor return type

src/Type/Parser/Lexer/AliasLexer.php, tests/Integration/Mapping/Fixture/DateInterval.php, tests/Integration/Mapping/Object/ExtendedDateIntervalMappingTest.php
=> fix: prevent infinite loop when class has parent class with same name

docs/pages/other/static-analysis.md
=> Update documentation on Psalm plugin

src/Definition/Repository/Cache/Compiler/AttributesCompiler.php
=> misc: improve attributes arguments compilation

src/Mapper/Tree/Message/MessageBuilder.php
=> fix: add missing `@psalm-pure` annotation to pure methods

src/Type/Parser/Lexer/AliasLexer.php, tests/Integration/Mapping/Namespace/NamespacedInterfaceInferringTest.php, tests/Integration/Mapping/Namespace/RegisteredStaticConstructorWithReturnTypeInDocBlockTest.php, tests/Integration/Mapping/Namespace/mapper-inferring-interface-from-non-class.php
=> fix: properly detect namespaced class in docblock

src/Definition/Repository/Cache/Compiler/TypeCompiler.php, tests/Functional/Definition/Repository/Cache/Compiler/TypeCompilerTest.php
=> fix: allow callable type to be compiled

src/Normalizer/Transformer/RecursiveTransformer.php, tests/Integration/Normalizer/NormalizerTest.php
=> fix: add default transformer for `DateTimeZone`

src/Library/Container.php, src/Mapper/Object/ArgumentsValues.php, src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/ObjectNodeBuilder.php, tests/Integration/Mapping/Other/SuperfluousKeysMappingTest.php
=> fix: handle single array mapping when a superfluous value is present

src/Type/Parser/Lexer/Token/ObjectToken.php, src/Type/Parser/Lexer/Token/VacantToken.php, src/Utility/Reflection/Reflection.php
=> qa: Replace Reflection-helper related phpstan-ignore-line by phpstan-assert-if-true

src/Definition/Repository/Reflection/TypeResolver/ParameterTypeResolver.php, tests/Functional/Definition/Repository/Reflection/TypeResolver/ParameterTypeResolverTest.php
=> fix: do not override invalid variadic parameter type

src/Type/Parser/Factory/Specifications/AliasSpecification.php, tests/Unit/Type/Parser/Factory/Specification/AliasSpecificationTest.php
=> fix: properly handle partial namespace signature

qa/PHPStan/Extension/TreeMapperPHPStanExtension.php
=> fix: support PHPStan extension for PHPStan v1 and v2

.github/workflows/benchmark.yml
Now that the master branch has the benchmark mechanism we can introduce a workflow that compares the PR code performance against the code on master.
This follows the work done in this PR https://github.com/CuyZ/Valinor/pull/594
=> feat: add benchmark workflow

src/Type/Parser/Exception/Enum/EnumCaseNotFound.php, src/Type/Types/EnumType.php, tests/Integration/Mapping/Object/EnumValuesMappingTest.php
=> fix: properly handle full namespaced enum type in docblock

src/Type/Parser/Lexer/Token/ArrayToken.php, tests/Functional/Type/Parser/LexingParserTest.php
=> misc: handle trailing comma in shaped array declaration

src/Mapper/Tree/Builder/InterfaceNodeBuilder.php, src/Mapper/Tree/Builder/UnionNodeBuilder.php, src/Mapper/Tree/Message/DefaultMessage.php, tests/Integration/Mapping/Object/ObjectValuesMappingTest.php, tests/Integration/Mapping/Object/UnionOfObjectsMappingTest.php
=> fix: properly handle interface with no implementation in union type

src/Mapper/Object/Argument.php, src/Mapper/Object/ArgumentsValues.php, src/Mapper/Object/Factory/StrictTypesObjectBuilderFactory.php, src/Mapper/Object/FunctionObjectBuilder.php, src/Mapper/Object/MethodObjectBuilder.php, src/Mapper/Object/NativeConstructorObjectBuilder.php, src/Mapper/Object/NativeEnumObjectBuilder.php, src/Mapper/Object/ObjectBuilder.php, src/Mapper/Object/ReflectionObjectBuilder.php, src/Mapper/Tree/Builder/ObjectNodeBuilder.php, src/Mapper/Tree/Builder/RootNodeBuilder.php, src/Mapper/Tree/Exception/CircularDependencyDetected.php, tests/Fake/Mapper/Object/FakeObjectBuilder.php, tests/Integration/Mapping/SingleNodeMappingTest.php, tests/Unit/Mapper/Object/NativeEnumObjectBuilderTest.php, tests/Unit/Mapper/Tree/Builder/RootNodeBuilderTest.php
=> fix: handle self-referential types in object constructors

src/Mapper/TypeArgumentsMapper.php, tests/Integration/Mapping/Closure/ArgumentsMappingTest.php
Transforms the source value if there is only one object argument, to ensure the source can contain flattened values:
```php
final class User
{
public string $name;
public string $email;
}
$function = fn (User $user) => …;
->argumentsMapper()
->mapArguments($function(...), [
'name' => 'John Doe',
'email' => 'john.doe@example.com',
]);
// Note that the key `user` is omitted in the source array.
```
=> feat: handle flattened values when mapping to a single object argument

docs/pages/serialization/common-transformers-examples.md, tests/Integration/Normalizer/CommonExamples/SinglePropertyObjectFlatteningFromAttributeTest.php, tests/Integration/Normalizer/CommonExamples/SinglePropertyObjectFlatteningTest.php
=> doc: add transformer example for single property objects flattening

src/Mapper/Tree/Builder/Node.php, src/Mapper/Tree/Builder/ObjectNodeBuilder.php, tests/Integration/Mapping/Object/EnumValuesMappingTest.php, tests/Integration/Mapping/Object/ObjectValuesMappingTest.php
=> fix: properly flatten node path when single value objects are used

src/Mapper/Object/Factory/SortingObjectBuilderFactory.php, src/Mapper/Tree/Builder/UnionNodeBuilder.php, src/Utility/TypeHelper.php, tests/Integration/Mapping/UnionMappingTest.php, tests/Unit/Utility/TypeHelperTest.php
=> fix: handle errors priorities when mapping to a union type
